# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				frog = true
				hoglin = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wither_skeleton = true
				piglin_brute = true
				item_frame = true
				horse = true
				ender_dragon = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				sheep = true
				player = true
				pufferfish = true
				villager = true
				zombie_villager = true
				tnt_minecart = true
				strider = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true

			[light_sources.settings.entities.create]
				super_glue = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				mauler = true

			[light_sources.settings.entities.cobblemon]
				empty_pokeball = true
				pokemon = true

			[light_sources.settings.entities.lilwings]
				grayling_butterfly = true
				aponi_butterfly = true
				red_applefly_butterfly = true
				swamp_hopper_butterfly = true
				painted_panther_butterfly = true

